### ISSUE TITLE
Revertions need to be made.

### ISSUE THREAD

**Issue by loralighte** [ICBIPL/Fibonacci#14]
Some of these I allowed, others I did not. Here are the non-compliant languages currently added:

- [Haskell](https://github.com/Random-People/Fibonacci/blob/master/fib.hs) Reason: Multi-function, which is fine if needed, however reversing it to a compliant version is needed.

(More will be added as I find them(

Here are the borderline languages (ones that are permitted to stay but on the line):
- [Ring](https://github.com/Random-People/Fibonacci/blob/master/fib.ring)
- [Racket](https://github.com/Random-People/Fibonacci/blob/master/fib.rkt)

Here is the one I fixed:
- [C++](https://github.com/Random-People/Fibonacci/blob/master/fib.cpp)

**Comment by coolshaurya** [comment]
Does the [go version](https://github.com/Random-People/Fibonacci/blob/master/fib.go) count as non-compliant?

Edit: I guess it doesn't. The order of the print statement before the loop is different from the pseudocode and inside the loop instead of `a = a + b` and `b = a + b` `a += b` and `b += a` is used but I don't think either of those can be considered  non-compliant.

**Comment by loralighte** [comment]
Go is compliant - Haskell is not. Go and Python are solid examples of what the code should function like

**Comment by no-defun-allowed** [comment]
> Reason: Multi-function, which is fine if needed

In that implementation, it is very needed in order to create an infinite sequence of Fibonacci numbers that we `takeWhile` from. One could write

```haskell
main = mapM_ print $ takeWhile (<1000000) fibs
  where fibs = [0, 1] ++ (map (uncurry (+)) $ zip fibs (tail fibs))
```
which is "one function" but equivalent in any other way.

(In hindsight, `zipWith` would make it shorter:)

```haskell
main = mapM_ print $ takeWhile (<1000000) fibs
  where fibs = [0, 1] ++ zipWith (+) fibs (tail fibs)
```

> - Racket

named `let` doesn't define any top-level functions. This should be fine.

> - Ring

I can't read this language, but it looks very similar to the example algorithm. What's the problem here?

**edit:** I found the "problem":

> The entire project uses the same setup for each language, with only small differences in each. The format being print the first two numbers of the sequence manually, set the two main variables, to finally use a while loop of the key variable being less than one million.

This is really not a good idea, because it just isn't what people do. 

People don't write while loops in Haskell, nor do they not use extended LOOP in Common Lisp, and they do use recursion for iteration in Racket. (To quote my girlfriend, who writes a whole lot more than I do, on the Haskell example: "whoever wrote that haskell code.... I'm so sorry for them, but that's not haskell, it is just an abuse of a do block...") Oh, and most programmers avoid special cases, such as printing the first two numbers of the sequence manually.

**Comment by loralighte** [comment]
I have given up changing everything back, but I am still working on getting as many languages in this repo as humanly possible.
